#!/usr/bin/env bash
# Bash script to Configure domain zone with 
# subdomain www pointed to load-balancer IP

if [ "$#" -lt 2 ]
then
    for sub_domain in www lb-01 web-01 web-02
    do
	dig "$sub_domain.$1" | awk -v sub_domain="$sub_domain" '/ANSWER SECTION:/ {
                                              getline; print "The subdomain",
                                              sub_domain,"is a",
                                              $(NF-1),"record and points",
                                              "to",$NF
                                             }'

   done
else
    dig "$2.$1" | awk -v sub_domain="$2" '/ANSWER SECTION:/ {
                                              getline; print "The subdomain",
                                              sub_domain,"is a",
                                              $(NF-1),"record and points",
                                              "to",$NF
                                             }'
fi
