#!/usr/bin/env bash
# Bash script that intall

sudo apt purge nginx
sudo apt autoremove
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start