#!/usr/bin/env bash
# Bash script that intall

sudo apt-get -y update
sudo apt-get -y install nginx
server {
listen 80;
ubuntu localhost;

location / {
return 200 "Hello World!\n";
}
}

#echo "Hello World!"
#echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
