#!/usr/bin/env bash
# Bash script that install and redirect to another page

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start