#!/usr/bin/env bash
# Bash script to configures a brand new Ubuntu machine to the requirements

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www/html
sudo touch /var/www/html/index.html
sudo touch /var/www/html/err_404.html
echo "Hello World!" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/err_404.html

config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /err_404.html;
    location /err_404.html {
      root /var/www/html;
      internal;
    }
}"

echo "$config" | sudo dd status=none of=/etc/nginx/sites-enabled/default

sudo service nginx restart
