#!/usr/bin/env bash
# Bash script that Install and configure HAproxy on lb-01 server.


balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
	server 330970-web-01 100.26.167.240:80 check
    server 330970-web-02 100.26.246.242:80 check
"	
	
# Update packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
