#!/usr/bin/env bash
# Bash script that Install and configure HAproxy on lb-01 server.


#!/usr/bin/env bash
# Bash script that Install and configure HAproxy on lb-01 server.

# Update packages
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get remove haproxy -y

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy=2.0.\*
sudo chown -R $USER:$USER /etc/haproxy/haproxy.cfg
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 330970-web-01 100.26.167.240:80 check\n\tserver 330970-web-02 3.83.227.79:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
