#!/usr/bin/env bash
# backup and compress my databases
sudo mysqldump -u root "$1" --all-databases > backup.sql
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
tar -czvf "$file_name" backup.sql
