#!/usr/bin/env bash
# Configures a server running, and listening on port 80 of other server’s
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx start
