#!/usr/bin/env bash
# Configures a server running, and listening on port 80 of other server’s
cd /etc/nginx/sites-enabled/ || exit;                                                                                                                                                                                                                                                   
rm default;                                                                                                                                               
ln -s /etc/nginx/sites-available/default default;                                                                                                         
service nginx restart 

