#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private key

# prevent permission denied 
eval $("ssh-agent")

#establishuing the requirement for connection
HOST="35.168.2.211"
USER="ubuntu"
PRIVATE_KEY="~/.ssh/school"

ssh-add $PRIVATE_KEY

# Connect to the server using SSH
ssh $USER@$HOST
